version: "3.9"

services:

  ai-tools:

    build: .

    container_name: ai-tools-service

    restart: unless-stopped

    ports:
      - "8000:8000"

    env_file:
      - .env

    volumes:
      - .:/app
